name = "PowerDynData"
uuid = "8af9307f-baed-4afb-b455-e9e9cc62a748"
authors = ["Hantao Cui"]
version = "0.1.0"

[deps]
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
julia = "1.9"
Parsers = "2"
InlineStrings = "1"
Tables = "1"
YAML = "0.4"
StructArrays = "0.6"
DocStringExtensions = "0.9"
PrecompileTools = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[targets]
test = ["Test", "DataFrames"]
