name = "PowerDynData"
uuid = "8af9307f-baed-4afb-b455-e9e9cc62a748"
authors = ["Hantao Cui"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
